// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Garcia_ancheta.Models;

public partial class Course
{
    public string Course_ID { get; set; }

    public string Course1 { get; set; }

    public string Tuition_Fee { get; set; }

    public string Start_Date { get; set; }

    public string End_Date { get; set; }

    public int Total_Subject { get; set; }
}