// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Garcia_ancheta.Models;

public partial class Room
{
    public string Room_ID { get; set; }

    public int Room_Number { get; set; }

    public string Floor { get; set; }

    public string Building { get; set; }

    public string Capacity { get; set; }
}