// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Garcia_ancheta.Models;

public partial class Section
{
    public string Section_ID { get; set; }

    public string Section_Name { get; set; }

    public string Current_Enrolled { get; set; }

    public string Room { get; set; }

    public string Adviser { get; set; }
}