// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Garcia_ancheta.Models;

public partial class Student
{
    public string Student_ID { get; set; }

    public string Last_Name { get; set; }

    public string First_Name { get; set; }

    public string Middle_Name { get; set; }

    public string Contact_Number { get; set; }
}