// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Garcia_ancheta.Models;

public partial class Teacher
{
    public string Teacher_ID { get; set; }

    public string Teacher_FirstName { get; set; }

    public string Teacher_MiddleName { get; set; }

    public string Teacher_LastName { get; set; }

    public string Faculty { get; set; }

    public string Specialization { get; set; }
}